-- ============================================================
-- Battery Passport Platform — PostgreSQL 18 Initial Schema
-- ============================================================

CREATE DATABASE battery_passport;

\c battery_passport;

-- Battery passport main table
CREATE TABLE IF NOT EXISTS battery_passport (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    passport_id     VARCHAR(64)  NOT NULL,
    serial_number   VARCHAR(128) NOT NULL,
    product_model   VARCHAR(64),
    manufacturer    VARCHAR(128),
    production_date DATE,
    rated_capacity  DECIMAL(10,2),
    rated_voltage   DECIMAL(10,2),
    initial_soh     DECIMAL(5,2),
    chemistry_type  VARCHAR(32),
    weight          DECIMAL(10,2),
    status          VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE',
    raw_json        TEXT,
    tenant_id       VARCHAR(32),
    create_time     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         SMALLINT     NOT NULL DEFAULT 0,
    CONSTRAINT uk_passport_id UNIQUE (passport_id)
);
CREATE INDEX IF NOT EXISTS idx_serial ON battery_passport (serial_number);
CREATE INDEX IF NOT EXISTS idx_tenant ON battery_passport (tenant_id);
CREATE INDEX IF NOT EXISTS idx_manufacturer ON battery_passport (manufacturer);
COMMENT ON TABLE battery_passport IS 'Battery passport table';
COMMENT ON COLUMN battery_passport.passport_id IS 'Passport number';
COMMENT ON COLUMN battery_passport.serial_number IS 'Battery serial number';
COMMENT ON COLUMN battery_passport.product_model IS 'Product model';
COMMENT ON COLUMN battery_passport.manufacturer IS 'Manufacturer';
COMMENT ON COLUMN battery_passport.production_date IS 'Production date';
COMMENT ON COLUMN battery_passport.rated_capacity IS 'Rated capacity (Ah)';
COMMENT ON COLUMN battery_passport.rated_voltage IS 'Rated voltage (V)';
COMMENT ON COLUMN battery_passport.initial_soh IS 'Initial state of health (%)';
COMMENT ON COLUMN battery_passport.chemistry_type IS 'Electrochemistry type';
COMMENT ON COLUMN battery_passport.weight IS 'Weight (kg)';
COMMENT ON COLUMN battery_passport.status IS 'Status';
COMMENT ON COLUMN battery_passport.raw_json IS 'Raw data JSON';
COMMENT ON COLUMN battery_passport.tenant_id IS 'Tenant ID (SaaS mode)';

-- Trace event table
CREATE TABLE IF NOT EXISTS trace_event (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    passport_id     VARCHAR(64)  NOT NULL,
    event_type      VARCHAR(32)  NOT NULL,
    operator        VARCHAR(64),
    location        VARCHAR(128),
    occurred_at     TIMESTAMP    NOT NULL,
    details         JSONB,
    tenant_id       VARCHAR(32),
    create_time     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         SMALLINT     NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_trace_passport ON trace_event (passport_id);
CREATE INDEX IF NOT EXISTS idx_trace_tenant ON trace_event (tenant_id);
COMMENT ON TABLE trace_event IS 'Trace event table';
COMMENT ON COLUMN trace_event.passport_id IS 'Related passport';
COMMENT ON COLUMN trace_event.event_type IS 'Event type';
COMMENT ON COLUMN trace_event.operator IS 'Operator';
COMMENT ON COLUMN trace_event.location IS 'Location';
COMMENT ON COLUMN trace_event.occurred_at IS 'Event time';
COMMENT ON COLUMN trace_event.details IS 'Event details (JSONB)';

-- Tenant table (SaaS mode)
CREATE TABLE IF NOT EXISTS sys_tenant (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_code     VARCHAR(32)  NOT NULL,
    tenant_name     VARCHAR(128) NOT NULL,
    contact_name    VARCHAR(64),
    contact_phone   VARCHAR(32),
    contact_email   VARCHAR(128),
    plan            VARCHAR(32),
    expire_date     DATE,
    status          VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE',
    create_time     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted         SMALLINT     NOT NULL DEFAULT 0,
    CONSTRAINT uk_tenant_code UNIQUE (tenant_code)
);
COMMENT ON TABLE sys_tenant IS 'Tenant table';
COMMENT ON COLUMN sys_tenant.tenant_code IS 'Tenant code';
COMMENT ON COLUMN sys_tenant.tenant_name IS 'Tenant name';
COMMENT ON COLUMN sys_tenant.plan IS 'Subscription plan';
COMMENT ON COLUMN sys_tenant.expire_date IS 'Expiry date';

-- System config table
CREATE TABLE IF NOT EXISTS sys_config (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_key      VARCHAR(64)  NOT NULL,
    config_value    TEXT         NOT NULL,
    description     VARCHAR(256),
    tenant_id       VARCHAR(32),
    create_time     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_config UNIQUE (tenant_id, config_key)
);
COMMENT ON TABLE sys_config IS 'Configuration table';
COMMENT ON COLUMN sys_config.config_key IS 'Config key';
COMMENT ON COLUMN sys_config.config_value IS 'Config value';
COMMENT ON COLUMN sys_config.description IS 'Description';

-- Initial data
INSERT INTO sys_tenant (tenant_code, tenant_name, plan, status)
VALUES ('trina', 'Trina Storage', 'enterprise', 'ACTIVE'),
       ('tuobang', 'Tuobang Co.', 'enterprise', 'ACTIVE')
ON CONFLICT (tenant_code) DO UPDATE SET tenant_name = EXCLUDED.tenant_name;

INSERT INTO sys_config (config_key, config_value, description)
VALUES ('battery.validation.capacity_deviation', '2.0', 'Capacity deviation threshold (%)');
