 server:
   port: 8080
 spring:
   application:
     name: gateway-service
   cloud:
     nacos:
       discovery:
         server-addr: ${NACOS_ADDR:127.0.0.1:8848}
     sentinel:
       transport:
         dashboard: ${SENTINEL_DASHBOARD:127.0.0.1:8858}
       eager: true
     gateway:
       globalcors:
         cors-configurations:
           '[/**]':
             allowed-origins: "*"
             allowed-methods: "*"
             allowed-headers: "*"
 
 battery:
   deploy:
     mode: ${DEPLOY_MODE:onpremise}
 ---
 spring:
   config:
     activate:
       on-profile: saas
 battery:
   deploy:
     mode: saas
 ---
 spring:
   config:
     activate:
       on-profile: onpremise
 battery:
   deploy:
     mode: onpremise
